In [3]:
#Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pymongo
from pymongo import MongoClient

In [4]:
#Entering UBC MongoDB System

CWL = 'ehdz1305'
SNUM = '22168454'

if CWL.strip() == "" or CWL == 'Put your CWL here' or SNUM.strip() == "" or SNUM == 'Put your SNUM here':
    print("You need up to update the value of the CWL and/or SNUM variables before proceeding.")
elif SNUM[0] == "a":
    print("You don't need to include the a here. Just include your student number as a string such as \"12345678\".")
else:
    connection_string = f"mongodb://{CWL}:a{SNUM}@localhost:27017/{CWL}"
    client = pymongo.MongoClient(connection_string)
    db = client[CWL]["project"]

In [6]:
post_covid_query = [
  {
    "$match":
      {
        'publishedDate': {
          '$gt': "2019-12-31"
        }
      }
  },
  {
    '$group':
      {
        '_id': "$genre",
        'Average_Ratings': {
          '$avg': "$stars"
        }
      }
  }
]

post_covid_data = pd.DataFrame(list(db['Book'].aggregate(post_covid_query)))

post_covid_data

                   _id  Average_Ratings
0              History         4.474468
1            Parenting         4.660870
2           Nonfiction         4.507692
3              Fiction         4.354878
4      Drama/Biography         4.493413
5                  NaN         4.507558
6         Family/Youth         4.375000
7               Sci-Fi         4.324000
8  Education/Knowledge         4.597000

In [7]:
pre_covid_query = [
  {
    "$match":
      {
        'publishedDate': {
          '$lte': "2019-12-31"
        }
      }
  },
  {
    '$group':
      {
        '_id': "$genre",
        'Average_Ratings': {
          '$avg': "$stars"
        }
      }
  }
]

pre_covid_data = pd.DataFrame(list(db['Book'].aggregate(pre_covid_query)))


pre_covid_data

                   _id  Average_Ratings
0              History         4.423810
1            Parenting         4.600000
2           Nonfiction         4.607692
3              Fiction         4.420000
4      Drama/Biography         4.464062
5                  NaN         4.520313
6         Family/Youth         4.468421
7               Sci-Fi         4.500000
8  Education/Knowledge         4.495876