# Step 3

#### Dont forget to tunnel....

In [1]:
#Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pymongo
from pymongo import MongoClient

In [2]:
#Entering UBC MongoDB System

CWL = 'ehdz1305'
SNUM = '22168454'

if CWL.strip() == "" or CWL == 'Put your CWL here' or SNUM.strip() == "" or SNUM == 'Put your SNUM here':
    print("You need up to update the value of the CWL and/or SNUM variables before proceeding.")
elif SNUM[0] == "a":
    print("You don't need to include the a here. Just include your student number as a string such as \"12345678\".")
else:
    connection_string = f"mongodb://{CWL}:a{SNUM}@localhost:27017/{CWL}"
    client = pymongo.MongoClient(connection_string)
    db = client[CWL]["project"]

In [3]:
#Reading cleaned data
Movie = pd.read_csv('cleaned_data/basics-2000.csv')
MovieRating =  pd.read_csv('cleaned_data/ratings-2000.csv')
MovieFinancial =  pd.read_csv('cleaned_data/imdb-data-2000.csv')
Book =  pd.read_csv('cleaned_data/kindle-2000.csv')

In [4]:
#Merging all Movie dataframes into a single one

#Making sure titles are normalized (using phase 3 method)
Movie["orig_title_norm"] = (Movie["originalTitle"].astype(str).str.lower().str.strip())


Movies = Movie.merge(MovieFinancial, on = 'orig_title_norm', how = 'inner')
Movies = Movies.merge(MovieRating, on = 'tconst', how = 'inner')


#Creating dictionaries in the financial and ratings section as stated in the schema
Movies['ratings'] = Movies[['averageRating', 'numVotes']].to_dict('records')
Movies['financial'] = Movies[['budget_x', 'revenue']].to_dict('records')

#Dropping unnecessary/repetitive columns
Movies = Movies.drop(columns = ['orig_title_norm','orig_title', 'budget_x', 
                       'revenue', 'averageRating', 'numVotes'])

Movies.iloc[::2]

,tconst,originalTitle,startYear,genres,date_x,ratings,financial
0,tt0293429,Mortal Kombat,2021.0,"Action,Adventure,Fantasy",2021-04-22,"{'averageRating': 6.1, 'numVotes': 203786}","{'budget_x': 55000000.0, 'revenue': 83508259.0}"
2,tt0437086,Alita: Battle Angel,2019.0,"Action,Adventure,Sci-Fi",2019-02-14,"{'averageRating': 7.3, 'numVotes': 322119}","{'budget_x': 170000000.0, 'revenue': 401900040.0}"
4,tt0448115,Shazam!,2019.0,"Action,Adventure,Comedy",2019-04-04,"{'averageRating': 7.0, 'numVotes': 411457}","{'budget_x': 85000000.0, 'revenue': 363563907.0}"
6,tt0493405,CHIPS,2017.0,"Action,Comedy,Crime",2017-03-24,"{'averageRating': 6.0, 'numVotes': 53906}","{'budget_x': 25000000.0, 'revenue': 23190292.0}"
8,tt0781524,Vendetta,2022.0,"Horror,Mystery,Thriller",2022-05-17,"{'averageRating': 5.6, 'numVotes': 42}","{'budget_x': 66890000.0, 'revenue': 448572309.6}"
...,...,...,...,...,...,...,...
1606,tt9777666,The Tomorrow War,2021.0,"Action,Adventure,Drama",2021-07-02,"{'averageRating': 6.6, 'numVotes': 251859}","{'budget_x': 200000000.0, 'revenue': 19220000.0}"
1608,tt9783730,On the Come Up,2022.0,"Comedy,Drama,Music",2022-09-23,"{'averageRating': 5.7, 'numVotes': 863}","{'budget_x': 5838800.0, 'revenue': 46000.0}"
1610,tt9848626,Hotel Transylvania: Transformania,2022.0,"Adventure,Animation,Comedy",2022-01-14,"{'averageRating': 6.0, 'numVotes': 46952}","{'budget_x': 116000000.0, 'revenue': 557205138.2}"
1612,tt9892546,Aladdin,2022.0,"Drama,Musical,Romance",2019-05-24,"{'averageRating': 5.1, 'numVotes': 56}","{'budget_x': 182000000.0, 'revenue': 104658751..."
1614,tt9896916,The Pilgrim's Progress,2019.0,"Adventure,Animation,Family",2019-04-18,"{'averageRating': 6.5, 'numVotes': 1061}","{'budget_x': 101000000.0, 'revenue': 893800197.2}"

In [5]:
Book.head()

,title,author,stars,reviews,category_id,publishedDate,category_name
0,The Covenant of Water (Oprah's Book Club),Abraham Verghese,4.7,31767,5,2023-05-02,Literature & Fiction
1,The Lost Bookshop: The most charming and uplif...,Evie Woods,4.5,12880,5,2023-06-22,Literature & Fiction
2,Happiness: A Novel,Danielle Steel,4.5,4705,5,2023-08-08,Literature & Fiction
3,Pineapple Street: A Novel,Jenny Jackson,4.0,17667,5,2023-03-07,Literature & Fiction
4,Romantic Comedy (Reese's Book Club): A Novel,Curtis Sittenfeld,4.1,8572,5,2023-04-04,Literature & Fiction

In [6]:
#using maps from phase 3 to have consistent genres:

#Applying map used in Phase 3
# apply genre/category mappings to create shared groups
Movies_genre_map = {
    "Action": "Fiction",
    "Adventure": "Fiction",
    "Fantasy": "Sci-Fi/Fantasy",
    "Sci-Fi": "Sci-Fi/Fantasy",
    "Comedy": "Fiction",
    "Romance": "Romance",
    "Drama": "Drama/Biography",
    "Biography": "Drama/Biography",
    "History": "History",
    "Documentary": "Education/Knowledge",
    "Family": "Family/Youth",
    "Animation": "Family/Youth"
}

Book_category_map = {
    "Literature & Fiction": "Fiction",
    "Science Fiction & Fantasy": "Sci-Fi/Fantasy",
    "Biographies & Memoirs": "Drama/Biography",
    "History": "History",
    "Education & Teaching": "Education/Knowledge",
    "Nonfiction": "Education/Knowledge",
    "Teen & Young Adult": "Family/Youth",
    "Parenting & Relationships": "Family/Youth",
    "Romance": "Romance",
    'Computers & Technology' : "Education/Knowledge",
    'Politics & Social Sciences' : "Education/Knowledge",
    'Foreign Language' :  "Education/Knowledge",
    'Self-Help' : "Education/Knowledge",
    'Travel': "Education/Knowledge",
    'Cookbooks, Food & Wine': "Education/Knowledge",
    'Religion & Spirituality': 'Spiritual',
    'LGBTQ+ eBooks' : "Education/Knowledge",
    'Arts & Photo graphy': "Education/Knowledge"
    
    
}

Book['genre'] = Book['category_name'].map(Book_category_map)


#Separating the Movies genres into a list of strings instead of single string for all genres:

genres = []

for i in Movies['genres']:
    
    if pd.isna(i):
        genres.append([])
        
    else:
        
        split = i.split(',')
        
        mapped_genres = []
    
        for g in split:
            
            if g in Movies_genre_map:
                
                mapped_genres.append(Movies_genre_map[g])
    
        genres.append(mapped_genres)

Movies = Movies.drop(columns = ['genres'])
Book = Book.drop(columns = ['category_name'])


Movies['genre'] = genres

In [7]:
#Inserting data into UBC MongoDB server

#Inserting Movies and Book to database
db['Movies'].delete_many({})
db['Movies'].insert_many(Movies.to_dict('records'))

db['Book'].delete_many({})
db['Book'].insert_many(Book.to_dict('records'))

InsertManyResult([ObjectId('69c43ec8d3331fd2a1fbe742'), ObjectId('69c43ec8d3331fd2a1fbe743'), ObjectId('69c43ec8d3331fd2a1fbe744'), ObjectId('69c43ec8d3331fd2a1fbe745'), ObjectId('69c43ec8d3331fd2a1fbe746'), ObjectId('69c43ec8d3331fd2a1fbe747'), ObjectId('69c43ec8d3331fd2a1fbe748'), ObjectId('69c43ec8d3331fd2a1fbe749'), ObjectId('69c43ec8d3331fd2a1fbe74a'), ObjectId('69c43ec8d3331fd2a1fbe74b'), ObjectId('69c43ec8d3331fd2a1fbe74c'), ObjectId('69c43ec8d3331fd2a1fbe74d'), ObjectId('69c43ec8d3331fd2a1fbe74e'), ObjectId('69c43ec8d3331fd2a1fbe74f'), ObjectId('69c43ec8d3331fd2a1fbe750'), ObjectId('69c43ec8d3331fd2a1fbe751'), ObjectId('69c43ec8d3331fd2a1fbe752'), ObjectId('69c43ec8d3331fd2a1fbe753'), ObjectId('69c43ec8d3331fd2a1fbe754'), ObjectId('69c43ec8d3331fd2a1fbe755'), ObjectId('69c43ec8d3331fd2a1fbe756'), ObjectId('69c43ec8d3331fd2a1fbe757'), ObjectId('69c43ec8d3331fd2a1fbe758'), ObjectId('69c43ec8d3331fd2a1fbe759'), ObjectId('69c43ec8d3331fd2a1fbe75a'), ObjectId('69c43ec8d3331fd2a1fbe75b'), ObjectId('69c43ec8d3331fd2a1fbe75c'), ObjectId('69c43ec8d3331fd2a1fbe75d'), ObjectId('69c43ec8d3331fd2a1fbe75e'), ObjectId('69c43ec8d3331fd2a1fbe75f'), ObjectId('69c43ec8d3331fd2a1fbe760'), ObjectId('69c43ec8d3331fd2a1fbe761'), ObjectId('69c43ec8d3331fd2a1fbe762'), ObjectId('69c43ec8d3331fd2a1fbe763'), ObjectId('69c43ec8d3331fd2a1fbe764'), ObjectId('69c43ec8d3331fd2a1fbe765'), ObjectId('69c43ec8d3331fd2a1fbe766'), ObjectId('69c43ec8d3331fd2a1fbe767'), ObjectId('69c43ec8d3331fd2a1fbe768'), ObjectId('69c43ec8d3331fd2a1fbe769'), ObjectId('69c43ec8d3331fd2a1fbe76a'), ObjectId('69c43ec8d3331fd2a1fbe76b'), ObjectId('69c43ec8d3331fd2a1fbe76c'), ObjectId('69c43ec8d3331fd2a1fbe76d'), ObjectId('69c43ec8d3331fd2a1fbe76e'), ObjectId('69c43ec8d3331fd2a1fbe76f'), ObjectId('69c43ec8d3331fd2a1fbe770'), ObjectId('69c43ec8d3331fd2a1fbe771'), ObjectId('69c43ec8d3331fd2a1fbe772'), ObjectId('69c43ec8d3331fd2a1fbe773'), ObjectId('69c43ec8d3331fd2a1fbe774'), ObjectId('69c43ec8d3331fd2a1fbe775'), ObjectId('69c43ec8d3331fd2a1fbe776'), ObjectId('69c43ec8d3331fd2a1fbe777'), ObjectId('69c43ec8d3331fd2a1fbe778'), ObjectId('69c43ec8d3331fd2a1fbe779'), ObjectId('69c43ec8d3331fd2a1fbe77a'), ObjectId('69c43ec8d3331fd2a1fbe77b'), ObjectId('69c43ec8d3331fd2a1fbe77c'), ObjectId('69c43ec8d3331fd2a1fbe77d'), ObjectId('69c43ec8d3331fd2a1fbe77e'), ObjectId('69c43ec8d3331fd2a1fbe77f'), ObjectId('69c43ec8d3331fd2a1fbe780'), ObjectId('69c43ec8d3331fd2a1fbe781'), ObjectId('69c43ec8d3331fd2a1fbe782'), ObjectId('69c43ec8d3331fd2a1fbe783'), ObjectId('69c43ec8d3331fd2a1fbe784'), ObjectId('69c43ec8d3331fd2a1fbe785'), ObjectId('69c43ec8d3331fd2a1fbe786'), ObjectId('69c43ec8d3331fd2a1fbe787'), ObjectId('69c43ec8d3331fd2a1fbe788'), ObjectId('69c43ec8d3331fd2a1fbe789'), ObjectId('69c43ec8d3331fd2a1fbe78a'), ObjectId('69c43ec8d3331fd2a1fbe78b'), ObjectId('69c43ec8d3331fd2a1fbe78c'), ObjectId('69c43ec8d3331fd2a1fbe78d'), ObjectId('69c43ec8d3331fd2a1fbe78e'), ObjectId('69c43ec8d3331fd2a1fbe78f'), ObjectId('69c43ec8d3331fd2a1fbe790'), ObjectId('69c43ec8d3331fd2a1fbe791'), ObjectId('69c43ec8d3331fd2a1fbe792'), ObjectId('69c43ec8d3331fd2a1fbe793'), ObjectId('69c43ec8d3331fd2a1fbe794'), ObjectId('69c43ec8d3331fd2a1fbe795'), ObjectId('69c43ec8d3331fd2a1fbe796'), ObjectId('69c43ec8d3331fd2a1fbe797'), ObjectId('69c43ec8d3331fd2a1fbe798'), ObjectId('69c43ec8d3331fd2a1fbe799'), ObjectId('69c43ec8d3331fd2a1fbe79a'), ObjectId('69c43ec8d3331fd2a1fbe79b'), ObjectId('69c43ec8d3331fd2a1fbe79c'), ObjectId('69c43ec8d3331fd2a1fbe79d'), ObjectId('69c43ec8d3331fd2a1fbe79e'), ObjectId('69c43ec8d3331fd2a1fbe79f'), ObjectId('69c43ec8d3331fd2a1fbe7a0'), ObjectId('69c43ec8d3331fd2a1fbe7a1'), ObjectId('69c43ec8d3331fd2a1fbe7a2'), ObjectId('69c43ec8d3331fd2a1fbe7a3'), ObjectId('69c43ec8d3331fd2a1fbe7a4'), ObjectId('69c43ec8d3331fd2a1fbe7a5'), ObjectId('69c43ec8d3331fd2a1fbe7a6'), ObjectId('69c43ec8d3331fd2a1fbe7a7'), ObjectId('69c43ec8d3331fd2a1fbe7a8'), ObjectId('69c43ec8d3331fd2a1fbe7a9'), ObjectId('69c43ec8d3331fd2a1fbe7aa'), ObjectId('69c43ec8d3331fd2a1fbe7ab'), ObjectId('69c43ec8d3331fd2a1fbe7ac'), ObjectId('69c43ec8d3331fd2a1fbe7ad'), ObjectId('69c43ec8d3331fd2a1fbe7ae'), ObjectId('69c43ec8d3331fd2a1fbe7af'), ObjectId('69c43ec8d3331fd2a1fbe7b0'), ObjectId('69c43ec8d3331fd2a1fbe7b1'), ObjectId('69c43ec8d3331fd2a1fbe7b2'), ObjectId('69c43ec8d3331fd2a1fbe7b3'), ObjectId('69c43ec8d3331fd2a1fbe7b4'), ObjectId('69c43ec8d3331fd2a1fbe7b5'), ObjectId('69c43ec8d3331fd2a1fbe7b6'), ObjectId('69c43ec8d3331fd2a1fbe7b7'), ObjectId('69c43ec8d3331fd2a1fbe7b8'), ObjectId('69c43ec8d3331fd2a1fbe7b9'), ObjectId('69c43ec8d3331fd2a1fbe7ba'), ObjectId('69c43ec8d3331fd2a1fbe7bb'), ObjectId('69c43ec8d3331fd2a1fbe7bc'), ObjectId('69c43ec8d3331fd2a1fbe7bd'), ObjectId('69c43ec8d3331fd2a1fbe7be'), ObjectId('69c43ec8d3331fd2a1fbe7bf'), ObjectId('69c43ec8d3331fd2a1fbe7c0'), ObjectId('69c43ec8d3331fd2a1fbe7c1'), ObjectId('69c43ec8d3331fd2a1fbe7c2'), ObjectId('69c43ec8d3331fd2a1fbe7c3'), ObjectId('69c43ec8d3331fd2a1fbe7c4'), ObjectId('69c43ec8d3331fd2a1fbe7c5'), ObjectId('69c43ec8d3331fd2a1fbe7c6'), ObjectId('69c43ec8d3331fd2a1fbe7c7'), ObjectId('69c43ec8d3331fd2a1fbe7c8'), ObjectId('69c43ec8d3331fd2a1fbe7c9'), ObjectId('69c43ec8d3331fd2a1fbe7ca'), ObjectId('69c43ec8d3331fd2a1fbe7cb'), ObjectId('69c43ec8d3331fd2a1fbe7cc'), ObjectId('69c43ec8d3331fd2a1fbe7cd'), ObjectId('69c43ec8d3331fd2a1fbe7ce'), ObjectId('69c43ec8d3331fd2a1fbe7cf'), ObjectId('69c43ec8d3331fd2a1fbe7d0'), ObjectId('69c43ec8d3331fd2a1fbe7d1'), ObjectId('69c43ec8d3331fd2a1fbe7d2'), ObjectId('69c43ec8d3331fd2a1fbe7d3'), ObjectId('69c43ec8d3331fd2a1fbe7d4'), ObjectId('69c43ec8d3331fd2a1fbe7d5'), ObjectId('69c43ec8d3331fd2a1fbe7d6'), ObjectId('69c43ec8d3331fd2a1fbe7d7'), ObjectId('69c43ec8d3331fd2a1fbe7d8'), ObjectId('69c43ec8d3331fd2a1fbe7d9'), ObjectId('69c43ec8d3331fd2a1fbe7da'), ObjectId('69c43ec8d3331fd2a1fbe7db'), ObjectId('69c43ec8d3331fd2a1fbe7dc'), ObjectId('69c43ec8d3331fd2a1fbe7dd'), ObjectId('69c43ec8d3331fd2a1fbe7de'), ObjectId('69c43ec8d3331fd2a1fbe7df'), ObjectId('69c43ec8d3331fd2a1fbe7e0'), ObjectId('69c43ec8d3331fd2a1fbe7e1'), ObjectId('69c43ec8d3331fd2a1fbe7e2'), ObjectId('69c43ec8d3331fd2a1fbe7e3'), ObjectId('69c43ec8d3331fd2a1fbe7e4'), ObjectId('69c43ec8d3331fd2a1fbe7e5'), ObjectId('69c43ec8d3331fd2a1fbe7e6'), ObjectId('69c43ec8d3331fd2a1fbe7e7'), ObjectId('69c43ec8d3331fd2a1fbe7e8'), ObjectId('69c43ec8d3331fd2a1fbe7e9'), ObjectId('69c43ec8d3331fd2a1fbe7ea'), ObjectId('69c43ec8d3331fd2a1fbe7eb'), ObjectId('69c43ec8d3331fd2a1fbe7ec'), ObjectId('69c43ec8d3331fd2a1fbe7ed'), ObjectId('69c43ec8d3331fd2a1fbe7ee'), ObjectId('69c43ec8d3331fd2a1fbe7ef'), ObjectId('69c43ec8d3331fd2a1fbe7f0'), ObjectId('69c43ec8d3331fd2a1fbe7f1'), ObjectId('69c43ec8d3331fd2a1fbe7f2'), ObjectId('69c43ec8d3331fd2a1fbe7f3'), ObjectId('69c43ec8d3331fd2a1fbe7f4'), ObjectId('69c43ec8d3331fd2a1fbe7f5'), ObjectId('69c43ec8d3331fd2a1fbe7f6'), ObjectId('69c43ec8d3331fd2a1fbe7f7'), ObjectId('69c43ec8d3331fd2a1fbe7f8'), ObjectId('69c43ec8d3331fd2a1fbe7f9'), ObjectId('69c43ec8d3331fd2a1fbe7fa'), ObjectId('69c43ec8d3331fd2a1fbe7fb'), ObjectId('69c43ec8d3331fd2a1fbe7fc'), ObjectId('69c43ec8d3331fd2a1fbe7fd'), ObjectId('69c43ec8d3331fd2a1fbe7fe'), ObjectId('69c43ec8d3331fd2a1fbe7ff'), ObjectId('69c43ec8d3331fd2a1fbe800'), ObjectId('69c43ec8d3331fd2a1fbe801'), ObjectId('69c43ec8d3331fd2a1fbe802'), ObjectId('69c43ec8d3331fd2a1fbe803'), ObjectId('69c43ec8d3331fd2a1fbe804'), ObjectId('69c43ec8d3331fd2a1fbe805'), ObjectId('69c43ec8d3331fd2a1fbe806'), ObjectId('69c43ec8d3331fd2a1fbe807'), ObjectId('69c43ec8d3331fd2a1fbe808'), ObjectId('69c43ec8d3331fd2a1fbe809'), ObjectId('69c43ec8d3331fd2a1fbe80a'), ObjectId('69c43ec8d3331fd2a1fbe80b'), ObjectId('69c43ec8d3331fd2a1fbe80c'), ObjectId('69c43ec8d3331fd2a1fbe80d'), ObjectId('69c43ec8d3331fd2a1fbe80e'), ObjectId('69c43ec8d3331fd2a1fbe80f'), ObjectId('69c43ec8d3331fd2a1fbe810'), ObjectId('69c43ec8d3331fd2a1fbe811'), ObjectId('69c43ec8d3331fd2a1fbe812'), ObjectId('69c43ec8d3331fd2a1fbe813'), ObjectId('69c43ec8d3331fd2a1fbe814'), ObjectId('69c43ec8d3331fd2a1fbe815'), ObjectId('69c43ec8d3331fd2a1fbe816'), ObjectId('69c43ec8d3331fd2a1fbe817'), ObjectId('69c43ec8d3331fd2a1fbe818'), ObjectId('69c43ec8d3331fd2a1fbe819'), ObjectId('69c43ec8d3331fd2a1fbe81a'), ObjectId('69c43ec8d3331fd2a1fbe81b'), ObjectId('69c43ec8d3331fd2a1fbe81c'), ObjectId('69c43ec8d3331fd2a1fbe81d'), ObjectId('69c43ec8d3331fd2a1fbe81e'), ObjectId('69c43ec8d3331fd2a1fbe81f'), ObjectId('69c43ec8d3331fd2a1fbe820'), ObjectId('69c43ec8d3331fd2a1fbe821'), ObjectId('69c43ec8d3331fd2a1fbe822'), ObjectId('69c43ec8d3331fd2a1fbe823'), ObjectId('69c43ec8d3331fd2a1fbe824'), ObjectId('69c43ec8d3331fd2a1fbe825'), ObjectId('69c43ec8d3331fd2a1fbe826'), ObjectId('69c43ec8d3331fd2a1fbe827'), ObjectId('69c43ec8d3331fd2a1fbe828'), ObjectId('69c43ec8d3331fd2a1fbe829'), ObjectId('69c43ec8d3331fd2a1fbe82a'), ObjectId('69c43ec8d3331fd2a1fbe82b'), ObjectId('69c43ec8d3331fd2a1fbe82c'), ObjectId('69c43ec8d3331fd2a1fbe82d'), ObjectId('69c43ec8d3331fd2a1fbe82e'), ObjectId('69c43ec8d3331fd2a1fbe82f'), ObjectId('69c43ec8d3331fd2a1fbe830'), ObjectId('69c43ec8d3331fd2a1fbe831'), ObjectId('69c43ec8d3331fd2a1fbe832'), ObjectId('69c43ec8d3331fd2a1fbe833'), ObjectId('69c43ec8d3331fd2a1fbe834'), ObjectId('69c43ec8d3331fd2a1fbe835'), ObjectId('69c43ec8d3331fd2a1fbe836'), ObjectId('69c43ec8d3331fd2a1fbe837'), ObjectId('69c43ec8d3331fd2a1fbe838'), ObjectId('69c43ec8d3331fd2a1fbe839'), ObjectId('69c43ec8d3331fd2a1fbe83a'), ObjectId('69c43ec8d3331fd2a1fbe83b'), ObjectId('69c43ec8d3331fd2a1fbe83c'), ObjectId('69c43ec8d3331fd2a1fbe83d'), ObjectId('69c43ec8d3331fd2a1fbe83e'), ObjectId('69c43ec8d3331fd2a1fbe83f'), ObjectId('69c43ec8d3331fd2a1fbe840'), ObjectId('69c43ec8d3331fd2a1fbe841'), ObjectId('69c43ec8d3331fd2a1fbe842'), ObjectId('69c43ec8d3331fd2a1fbe843'), ObjectId('69c43ec8d3331fd2a1fbe844'), ObjectId('69c43ec8d3331fd2a1fbe845'), ObjectId('69c43ec8d3331fd2a1fbe846'), ObjectId('69c43ec8d3331fd2a1fbe847'), ObjectId('69c43ec8d3331fd2a1fbe848'), ObjectId('69c43ec8d3331fd2a1fbe849'), ObjectId('69c43ec8d3331fd2a1fbe84a'), ObjectId('69c43ec8d3331fd2a1fbe84b'), ObjectId('69c43ec8d3331fd2a1fbe84c'), ObjectId('69c43ec8d3331fd2a1fbe84d'), ObjectId('69c43ec8d3331fd2a1fbe84e'), ObjectId('69c43ec8d3331fd2a1fbe84f'), ObjectId('69c43ec8d3331fd2a1fbe850'), ObjectId('69c43ec8d3331fd2a1fbe851'), ObjectId('69c43ec8d3331fd2a1fbe852'), ObjectId('69c43ec8d3331fd2a1fbe853'), ObjectId('69c43ec8d3331fd2a1fbe854'), ObjectId('69c43ec8d3331fd2a1fbe855'), ObjectId('69c43ec8d3331fd2a1fbe856'), ObjectId('69c43ec8d3331fd2a1fbe857'), ObjectId('69c43ec8d3331fd2a1fbe858'), ObjectId('69c43ec8d3331fd2a1fbe859'), ObjectId('69c43ec8d3331fd2a1fbe85a'), ObjectId('69c43ec8d3331fd2a1fbe85b'), ObjectId('69c43ec8d3331fd2a1fbe85c'), ObjectId('69c43ec8d3331fd2a1fbe85d'), ObjectId('69c43ec8d3331fd2a1fbe85e'), ObjectId('69c43ec8d3331fd2a1fbe85f'), ObjectId('69c43ec8d3331fd2a1fbe860'), ObjectId('69c43ec8d3331fd2a1fbe861'), ObjectId('69c43ec8d3331fd2a1fbe862'), ObjectId('69c43ec8d3331fd2a1fbe863'), ObjectId('69c43ec8d3331fd2a1fbe864'), ObjectId('69c43ec8d3331fd2a1fbe865'), ObjectId('69c43ec8d3331fd2a1fbe866'), ObjectId('69c43ec8d3331fd2a1fbe867'), ObjectId('69c43ec8d3331fd2a1fbe868'), ObjectId('69c43ec8d3331fd2a1fbe869'), ObjectId('69c43ec8d3331fd2a1fbe86a'), ObjectId('69c43ec8d3331fd2a1fbe86b'), ObjectId('69c43ec8d3331fd2a1fbe86c'), ObjectId('69c43ec8d3331fd2a1fbe86d'), ObjectId('69c43ec8d3331fd2a1fbe86e'), ObjectId('69c43ec8d3331fd2a1fbe86f'), ObjectId('69c43ec8d3331fd2a1fbe870'), ObjectId('69c43ec8d3331fd2a1fbe871'), ObjectId('69c43ec8d3331fd2a1fbe872'), ObjectId('69c43ec8d3331fd2a1fbe873'), ObjectId('69c43ec8d3331fd2a1fbe874'), ObjectId('69c43ec8d3331fd2a1fbe875'), ObjectId('69c43ec8d3331fd2a1fbe876'), ObjectId('69c43ec8d3331fd2a1fbe877'), ObjectId('69c43ec8d3331fd2a1fbe878'), ObjectId('69c43ec8d3331fd2a1fbe879'), ObjectId('69c43ec8d3331fd2a1fbe87a'), ObjectId('69c43ec8d3331fd2a1fbe87b'), ObjectId('69c43ec8d3331fd2a1fbe87c'), ObjectId('69c43ec8d3331fd2a1fbe87d'), ObjectId('69c43ec8d3331fd2a1fbe87e'), ObjectId('69c43ec8d3331fd2a1fbe87f'), ObjectId('69c43ec8d3331fd2a1fbe880'), ObjectId('69c43ec8d3331fd2a1fbe881'), ObjectId('69c43ec8d3331fd2a1fbe882'), ObjectId('69c43ec8d3331fd2a1fbe883'), ObjectId('69c43ec8d3331fd2a1fbe884'), ObjectId('69c43ec8d3331fd2a1fbe885'), ObjectId('69c43ec8d3331fd2a1fbe886'), ObjectId('69c43ec8d3331fd2a1fbe887'), ObjectId('69c43ec8d3331fd2a1fbe888'), ObjectId('69c43ec8d3331fd2a1fbe889'), ObjectId('69c43ec8d3331fd2a1fbe88a'), ObjectId('69c43ec8d3331fd2a1fbe88b'), ObjectId('69c43ec8d3331fd2a1fbe88c'), ObjectId('69c43ec8d3331fd2a1fbe88d'), ObjectId('69c43ec8d3331fd2a1fbe88e'), ObjectId('69c43ec8d3331fd2a1fbe88f'), ObjectId('69c43ec8d3331fd2a1fbe890'), ObjectId('69c43ec8d3331fd2a1fbe891'), ObjectId('69c43ec8d3331fd2a1fbe892'), ObjectId('69c43ec8d3331fd2a1fbe893'), ObjectId('69c43ec8d3331fd2a1fbe894'), ObjectId('69c43ec8d3331fd2a1fbe895'), ObjectId('69c43ec8d3331fd2a1fbe896'), ObjectId('69c43ec8d3331fd2a1fbe897'), ObjectId('69c43ec8d3331fd2a1fbe898'), ObjectId('69c43ec8d3331fd2a1fbe899'), ObjectId('69c43ec8d3331fd2a1fbe89a'), ObjectId('69c43ec8d3331fd2a1fbe89b'), ObjectId('69c43ec8d3331fd2a1fbe89c'), ObjectId('69c43ec8d3331fd2a1fbe89d'), ObjectId('69c43ec8d3331fd2a1fbe89e'), ObjectId('69c43ec8d3331fd2a1fbe89f'), ObjectId('69c43ec8d3331fd2a1fbe8a0'), ObjectId('69c43ec8d3331fd2a1fbe8a1'), ObjectId('69c43ec8d3331fd2a1fbe8a2'), ObjectId('69c43ec8d3331fd2a1fbe8a3'), ObjectId('69c43ec8d3331fd2a1fbe8a4'), ObjectId('69c43ec8d3331fd2a1fbe8a5'), ObjectId('69c43ec8d3331fd2a1fbe8a6'), ObjectId('69c43ec8d3331fd2a1fbe8a7'), ObjectId('69c43ec8d3331fd2a1fbe8a8'), ObjectId('69c43ec8d3331fd2a1fbe8a9'), ObjectId('69c43ec8d3331fd2a1fbe8aa'), ObjectId('69c43ec8d3331fd2a1fbe8ab'), ObjectId('69c43ec8d3331fd2a1fbe8ac'), ObjectId('69c43ec8d3331fd2a1fbe8ad'), ObjectId('69c43ec8d3331fd2a1fbe8ae'), ObjectId('69c43ec8d3331fd2a1fbe8af'), ObjectId('69c43ec8d3331fd2a1fbe8b0'), ObjectId('69c43ec8d3331fd2a1fbe8b1'), ObjectId('69c43ec8d3331fd2a1fbe8b2'), ObjectId('69c43ec8d3331fd2a1fbe8b3'), ObjectId('69c43ec8d3331fd2a1fbe8b4'), ObjectId('69c43ec8d3331fd2a1fbe8b5'), ObjectId('69c43ec8d3331fd2a1fbe8b6'), ObjectId('69c43ec8d3331fd2a1fbe8b7'), ObjectId('69c43ec8d3331fd2a1fbe8b8'), ObjectId('69c43ec8d3331fd2a1fbe8b9'), ObjectId('69c43ec8d3331fd2a1fbe8ba'), ObjectId('69c43ec8d3331fd2a1fbe8bb'), ObjectId('69c43ec8d3331fd2a1fbe8bc'), ObjectId('69c43ec8d3331fd2a1fbe8bd'), ObjectId('69c43ec8d3331fd2a1fbe8be'), ObjectId('69c43ec8d3331fd2a1fbe8bf'), ObjectId('69c43ec8d3331fd2a1fbe8c0'), ObjectId('69c43ec8d3331fd2a1fbe8c1'), ObjectId('69c43ec8d3331fd2a1fbe8c2'), ObjectId('69c43ec8d3331fd2a1fbe8c3'), ObjectId('69c43ec8d3331fd2a1fbe8c4'), ObjectId('69c43ec8d3331fd2a1fbe8c5'), ObjectId('69c43ec8d3331fd2a1fbe8c6'), ObjectId('69c43ec8d3331fd2a1fbe8c7'), ObjectId('69c43ec8d3331fd2a1fbe8c8'), ObjectId('69c43ec8d3331fd2a1fbe8c9'), ObjectId('69c43ec8d3331fd2a1fbe8ca'), ObjectId('69c43ec8d3331fd2a1fbe8cb'), ObjectId('69c43ec8d3331fd2a1fbe8cc'), ObjectId('69c43ec8d3331fd2a1fbe8cd'), ObjectId('69c43ec8d3331fd2a1fbe8ce'), ObjectId('69c43ec8d3331fd2a1fbe8cf'), ObjectId('69c43ec8d3331fd2a1fbe8d0'), ObjectId('69c43ec8d3331fd2a1fbe8d1'), ObjectId('69c43ec8d3331fd2a1fbe8d2'), ObjectId('69c43ec8d3331fd2a1fbe8d3'), ObjectId('69c43ec8d3331fd2a1fbe8d4'), ObjectId('69c43ec8d3331fd2a1fbe8d5'), ObjectId('69c43ec8d3331fd2a1fbe8d6'), ObjectId('69c43ec8d3331fd2a1fbe8d7'), ObjectId('69c43ec8d3331fd2a1fbe8d8'), ObjectId('69c43ec8d3331fd2a1fbe8d9'), ObjectId('69c43ec8d3331fd2a1fbe8da'), ObjectId('69c43ec8d3331fd2a1fbe8db'), ObjectId('69c43ec8d3331fd2a1fbe8dc'), ObjectId('69c43ec8d3331fd2a1fbe8dd'), ObjectId('69c43ec8d3331fd2a1fbe8de'), ObjectId('69c43ec8d3331fd2a1fbe8df'), ObjectId('69c43ec8d3331fd2a1fbe8e0'), ObjectId('69c43ec8d3331fd2a1fbe8e1'), ObjectId('69c43ec8d3331fd2a1fbe8e2'), ObjectId('69c43ec8d3331fd2a1fbe8e3'), ObjectId('69c43ec8d3331fd2a1fbe8e4'), ObjectId('69c43ec8d3331fd2a1fbe8e5'), ObjectId('69c43ec8d3331fd2a1fbe8e6'), ObjectId('69c43ec8d3331fd2a1fbe8e7'), ObjectId('69c43ec8d3331fd2a1fbe8e8'), ObjectId('69c43ec8d3331fd2a1fbe8e9'), ObjectId('69c43ec8d3331fd2a1fbe8ea'), ObjectId('69c43ec8d3331fd2a1fbe8eb'), ObjectId('69c43ec8d3331fd2a1fbe8ec'), ObjectId('69c43ec8d3331fd2a1fbe8ed'), ObjectId('69c43ec8d3331fd2a1fbe8ee'), ObjectId('69c43ec8d3331fd2a1fbe8ef'), ObjectId('69c43ec8d3331fd2a1fbe8f0'), ObjectId('69c43ec8d3331fd2a1fbe8f1'), ObjectId('69c43ec8d3331fd2a1fbe8f2'), ObjectId('69c43ec8d3331fd2a1fbe8f3'), ObjectId('69c43ec8d3331fd2a1fbe8f4'), ObjectId('69c43ec8d3331fd2a1fbe8f5'), ObjectId('69c43ec8d3331fd2a1fbe8f6'), ObjectId('69c43ec8d3331fd2a1fbe8f7'), ObjectId('69c43ec8d3331fd2a1fbe8f8'), ObjectId('69c43ec8d3331fd2a1fbe8f9'), ObjectId('69c43ec8d3331fd2a1fbe8fa'), ObjectId('69c43ec8d3331fd2a1fbe8fb'), ObjectId('69c43ec8d3331fd2a1fbe8fc'), ObjectId('69c43ec8d3331fd2a1fbe8fd'), ObjectId('69c43ec8d3331fd2a1fbe8fe'), ObjectId('69c43ec8d3331fd2a1fbe8ff'), ObjectId('69c43ec8d3331fd2a1fbe900'), ObjectId('69c43ec8d3331fd2a1fbe901'), ObjectId('69c43ec8d3331fd2a1fbe902'), ObjectId('69c43ec8d3331fd2a1fbe903'), ObjectId('69c43ec8d3331fd2a1fbe904'), ObjectId('69c43ec8d3331fd2a1fbe905'), ObjectId('69c43ec8d3331fd2a1fbe906'), ObjectId('69c43ec8d3331fd2a1fbe907'), ObjectId('69c43ec8d3331fd2a1fbe908'), ObjectId('69c43ec8d3331fd2a1fbe909'), ObjectId('69c43ec8d3331fd2a1fbe90a'), ObjectId('69c43ec8d3331fd2a1fbe90b'), ObjectId('69c43ec8d3331fd2a1fbe90c'), ObjectId('69c43ec8d3331fd2a1fbe90d'), ObjectId('69c43ec8d3331fd2a1fbe90e'), ObjectId('69c43ec8d3331fd2a1fbe90f'), ObjectId('69c43ec8d3331fd2a1fbe910'), ObjectId('69c43ec8d3331fd2a1fbe911'), ObjectId('69c43ec8d3331fd2a1fbe912'), ObjectId('69c43ec8d3331fd2a1fbe913'), ObjectId('69c43ec8d3331fd2a1fbe914'), ObjectId('69c43ec8d3331fd2a1fbe915'), ObjectId('69c43ec8d3331fd2a1fbe916'), ObjectId('69c43ec8d3331fd2a1fbe917'), ObjectId('69c43ec8d3331fd2a1fbe918'), ObjectId('69c43ec8d3331fd2a1fbe919'), ObjectId('69c43ec8d3331fd2a1fbe91a'), ObjectId('69c43ec8d3331fd2a1fbe91b'), ObjectId('69c43ec8d3331fd2a1fbe91c'), ObjectId('69c43ec8d3331fd2a1fbe91d'), ObjectId('69c43ec8d3331fd2a1fbe91e'), ObjectId('69c43ec8d3331fd2a1fbe91f'), ObjectId('69c43ec8d3331fd2a1fbe920'), ObjectId('69c43ec8d3331fd2a1fbe921'), ObjectId('69c43ec8d3331fd2a1fbe922'), ObjectId('69c43ec8d3331fd2a1fbe923'), ObjectId('69c43ec8d3331fd2a1fbe924'), ObjectId('69c43ec8d3331fd2a1fbe925'), ObjectId('69c43ec8d3331fd2a1fbe926'), ObjectId('69c43ec8d3331fd2a1fbe927'), ObjectId('69c43ec8d3331fd2a1fbe928'), ObjectId('69c43ec8d3331fd2a1fbe929'), ObjectId('69c43ec8d3331fd2a1fbe92a'), ObjectId('69c43ec8d3331fd2a1fbe92b'), ObjectId('69c43ec8d3331fd2a1fbe92c'), ObjectId('69c43ec8d3331fd2a1fbe92d'), ObjectId('69c43ec8d3331fd2a1fbe92e'), ObjectId('69c43ec8d3331fd2a1fbe92f'), ObjectId('69c43ec8d3331fd2a1fbe930'), ObjectId('69c43ec8d3331fd2a1fbe931'), ObjectId('69c43ec8d3331fd2a1fbe932'), ObjectId('69c43ec8d3331fd2a1fbe933'), ObjectId('69c43ec8d3331fd2a1fbe934'), ObjectId('69c43ec8d3331fd2a1fbe935'), ObjectId('69c43ec8d3331fd2a1fbe936'), ObjectId('69c43ec8d3331fd2a1fbe937'), ObjectId('69c43ec8d3331fd2a1fbe938'), ObjectId('69c43ec8d3331fd2a1fbe939'), ObjectId('69c43ec8d3331fd2a1fbe93a'), ObjectId('69c43ec8d3331fd2a1fbe93b'), ObjectId('69c43ec8d3331fd2a1fbe93c'), ObjectId('69c43ec8d3331fd2a1fbe93d'), ObjectId('69c43ec8d3331fd2a1fbe93e'), ObjectId('69c43ec8d3331fd2a1fbe93f'), ObjectId('69c43ec8d3331fd2a1fbe940'), ObjectId('69c43ec8d3331fd2a1fbe941'), ObjectId('69c43ec8d3331fd2a1fbe942'), ObjectId('69c43ec8d3331fd2a1fbe943'), ObjectId('69c43ec8d3331fd2a1fbe944'), ObjectId('69c43ec8d3331fd2a1fbe945'), ObjectId('69c43ec8d3331fd2a1fbe946'), ObjectId('69c43ec8d3331fd2a1fbe947'), ObjectId('69c43ec8d3331fd2a1fbe948'), ObjectId('69c43ec8d3331fd2a1fbe949'), ObjectId('69c43ec8d3331fd2a1fbe94a'), ObjectId('69c43ec8d3331fd2a1fbe94b'), ObjectId('69c43ec8d3331fd2a1fbe94c'), ObjectId('69c43ec8d3331fd2a1fbe94d'), ObjectId('69c43ec8d3331fd2a1fbe94e'), ObjectId('69c43ec8d3331fd2a1fbe9