# Step 3

#### Dont forget to tunnel....

In [1]:
#Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pymongo
from pymongo import MongoClient

In [2]:
#Entering UBC MongoDB System

CWL = 'ehdz1305'
SNUM = '22168454'

if CWL.strip() == "" or CWL == 'Put your CWL here' or SNUM.strip() == "" or SNUM == 'Put your SNUM here':
    print("You need up to update the value of the CWL and/or SNUM variables before proceeding.")
elif SNUM[0] == "a":
    print("You don't need to include the a here. Just include your student number as a string such as \"12345678\".")
else:
    connection_string = f"mongodb://{CWL}:a{SNUM}@localhost:27017/{CWL}"
    client = pymongo.MongoClient(connection_string)
    db = client[CWL]["project"]

In [3]:
#Reading cleaned data
Movie = pd.read_csv('cleaned_data/basics-2000.csv')
MovieRating =  pd.read_csv('cleaned_data/ratings-2000.csv')
MovieFinancial =  pd.read_csv('cleaned_data/imdb-data-2000.csv')
Book =  pd.read_csv('cleaned_data/kindle-2000.csv')

In [4]:
#Merging all Movie dataframes into a single one

#Making sure titles are normalized (using phase 3 method)
Movie["orig_title_norm"] = (Movie["originalTitle"].astype(str).str.lower().str.strip())


Movies = Movie.merge(MovieFinancial, on = 'orig_title_norm', how = 'inner')
Movies = Movies.merge(MovieRating, on = 'tconst', how = 'inner')


#Creating dictionaries in the financial and ratings section as stated in the schema
Movies['ratings'] = Movies[['averageRating', 'numVotes']].to_dict('records')
Movies['financial'] = Movies[['budget_x', 'revenue']].to_dict('records')

#Dropping unnecessary/repetitive columns
Movies = Movies.drop(columns = ['orig_title_norm','orig_title', 'budget_x', 
                       'revenue', 'averageRating', 'numVotes'])

Movies.head()

,tconst,originalTitle,startYear,genres,date_x,ratings,financial
0,tt0293429,Mortal Kombat,2021.0,"Action,Adventure,Fantasy",2021-04-22,"{'averageRating': 6.1, 'numVotes': 203786}","{'budget_x': 55000000.0, 'revenue': 83508259.0}"
1,tt0293429,Mortal Kombat,2021.0,"Action,Adventure,Fantasy",2021-04-22,"{'averageRating': 6.1, 'numVotes': 203786}","{'budget_x': 20000000.0, 'revenue': 122133227.0}"
2,tt0437086,Alita: Battle Angel,2019.0,"Action,Adventure,Sci-Fi",2019-02-14,"{'averageRating': 7.3, 'numVotes': 322119}","{'budget_x': 170000000.0, 'revenue': 401900040.0}"
3,tt0439572,The Flash,2023.0,"Action,Adventure,Fantasy",2023-06-16,"{'averageRating': 6.6, 'numVotes': 245757}","{'budget_x': 200000000.0, 'revenue': 1240261.6}"
4,tt0448115,Shazam!,2019.0,"Action,Adventure,Comedy",2019-04-04,"{'averageRating': 7.0, 'numVotes': 411457}","{'budget_x': 85000000.0, 'revenue': 363563907.0}"

In [5]:
Book.head()

,title,author,stars,reviews,category_id,publishedDate,category_name
0,The Covenant of Water (Oprah's Book Club),Abraham Verghese,4.7,31767,5,2023-05-02,Literature & Fiction
1,The Lost Bookshop: The most charming and uplif...,Evie Woods,4.5,12880,5,2023-06-22,Literature & Fiction
2,Happiness: A Novel,Danielle Steel,4.5,4705,5,2023-08-08,Literature & Fiction
3,Pineapple Street: A Novel,Jenny Jackson,4.0,17667,5,2023-03-07,Literature & Fiction
4,Romantic Comedy (Reese's Book Club): A Novel,Curtis Sittenfeld,4.1,8572,5,2023-04-04,Literature & Fiction

In [6]:
#using maps from phase 3 to have same genres:

#Applying map used in Phase 3
# apply genre/category mappings to create shared groups
Movies_genre_map = {
    "Action": "Fiction",
    "Adventure": "Fiction",
    "Fantasy": "Sci-Fi/Fantasy",
    "Sci-Fi": "Sci-Fi/Fantasy",
    "Comedy": "Fiction",
    "Romance": "Romance",
    "Drama": "Drama/Biography",
    "Biography": "Drama/Biography",
    "History": "History",
    "Documentary": "Education/Knowledge",
    "Family": "Family/Youth",
    "Animation": "Family/Youth"
}

Book_category_map = {
    "Literature & Fiction": "Fiction",
    "Science Fiction & Fantasy": "Sci-Fi/Fantasy",
    "Biographies & Memoirs": "Drama/Biography",
    "History": "History",
    "Education & Teaching": "Education/Knowledge",
    "Nonfiction": "Education/Knowledge",
    "Teen & Young Adult": "Family/Youth",
    "Parenting & Relationships": "Family/Youth",
    "Romance": "Romance"
}

Book['genre_group'] = Book['category_name'].map(Book_category_map)


#Separating the Movies genres into a list of strings instead of single string for all genres:

genres = []

for i in Movies['genres']:
    if pd.isna(i):
        genres.append([])
    else:
        
        split = i.split(',')
        mapped_genres = []
    
        for g in split:
            if g in Movies_genre_map:
                mapped_genres.append(Movies_genre_map[g])
    
        genres.append(mapped_genres)


Movies['genre_group'] = genres
Movies = Movies.drop(columns = ['genres'])

In [7]:
Movies

,tconst,originalTitle,startYear,date_x,ratings,financial,genre_group
0,tt0293429,Mortal Kombat,2021.0,2021-04-22,"{'averageRating': 6.1, 'numVotes': 203786}","{'budget_x': 55000000.0, 'revenue': 83508259.0}","[Fiction, Fiction, Sci-Fi/Fantasy]"
1,tt0293429,Mortal Kombat,2021.0,2021-04-22,"{'averageRating': 6.1, 'numVotes': 203786}","{'budget_x': 20000000.0, 'revenue': 122133227.0}","[Fiction, Fiction, Sci-Fi/Fantasy]"
2,tt0437086,Alita: Battle Angel,2019.0,2019-02-14,"{'averageRating': 7.3, 'numVotes': 322119}","{'budget_x': 170000000.0, 'revenue': 401900040.0}","[Fiction, Fiction, Sci-Fi/Fantasy]"
3,tt0439572,The Flash,2023.0,2023-06-16,"{'averageRating': 6.6, 'numVotes': 245757}","{'budget_x': 200000000.0, 'revenue': 1240261.6}","[Fiction, Fiction, Sci-Fi/Fantasy]"
4,tt0448115,Shazam!,2019.0,2019-04-04,"{'averageRating': 7.0, 'numVotes': 411457}","{'budget_x': 85000000.0, 'revenue': 363563907.0}","[Fiction, Fiction, Fiction]"
...,...,...,...,...,...,...,...
1611,tt9853500,Bandit,2022.0,2022-09-23,"{'averageRating': 6.5, 'numVotes': 17352}","{'budget_x': 115000000.0, 'revenue': 484414431.0}","[Drama/Biography, Drama/Biography]"
1612,tt9892546,Aladdin,2022.0,2019-05-24,"{'averageRating': 5.1, 'numVotes': 56}","{'budget_x': 182000000.0, 'revenue': 104658751...","[Drama/Biography, Romance]"
1613,tt9892546,Aladdin,2022.0,2019-05-24,"{'averageRating': 5.1, 'numVotes': 56}","{'budget_x': 28000000.0, 'revenue': 504050219.0}","[Drama/Biography, Romance]"
1614,tt9896916,The Pilgrim's Progress,2019.0,2019-04-18,"{'averageRating': 6.5, 'numVotes': 1061}","{'budget_x': 101000000.0, 'revenue': 893800197.2}","[Fiction, Family/Youth, Family/Youth]"
1615,tt9898844,The Hunting,2021.0,2022-01-21,"{'averageRating': 3.1, 'numVotes': 572}","{'budget_x': 147180000.0, 'revenue': 222629230.6}",[]

In [8]:
#Inserting data into UBC MongoDB server

#Inserting Movies and Book to database
db['Movies'].delete_many({})
db['Movies'].insert_many(Movies.to_dict('records'))

db['Book'].delete_many({})
db['Book'].insert_many(Book.to_dict('records'))

InsertManyResult([ObjectId('69c37715b1c5d6989e3ab54d'), ObjectId('69c37715b1c5d6989e3ab54e'), ObjectId('69c37715b1c5d6989e3ab54f'), ObjectId('69c37715b1c5d6989e3ab550'), ObjectId('69c37715b1c5d6989e3ab551'), ObjectId('69c37715b1c5d6989e3ab552'), ObjectId('69c37715b1c5d6989e3ab553'), ObjectId('69c37715b1c5d6989e3ab554'), ObjectId('69c37715b1c5d6989e3ab555'), ObjectId('69c37715b1c5d6989e3ab556'), ObjectId('69c37715b1c5d6989e3ab557'), ObjectId('69c37715b1c5d6989e3ab558'), ObjectId('69c37715b1c5d6989e3ab559'), ObjectId('69c37715b1c5d6989e3ab55a'), ObjectId('69c37715b1c5d6989e3ab55b'), ObjectId('69c37715b1c5d6989e3ab55c'), ObjectId('69c37715b1c5d6989e3ab55d'), ObjectId('69c37715b1c5d6989e3ab55e'), ObjectId('69c37715b1c5d6989e3ab55f'), ObjectId('69c37715b1c5d6989e3ab560'), ObjectId('69c37715b1c5d6989e3ab561'), ObjectId('69c37715b1c5d6989e3ab562'), ObjectId('69c37715b1c5d6989e3ab563'), ObjectId('69c37715b1c5d6989e3ab564'), ObjectId('69c37715b1c5d6989e3ab565'), ObjectId('69c37715b1c5d6989e3ab566'), ObjectId('69c37715b1c5d6989e3ab567'), ObjectId('69c37715b1c5d6989e3ab568'), ObjectId('69c37715b1c5d6989e3ab569'), ObjectId('69c37715b1c5d6989e3ab56a'), ObjectId('69c37715b1c5d6989e3ab56b'), ObjectId('69c37715b1c5d6989e3ab56c'), ObjectId('69c37715b1c5d6989e3ab56d'), ObjectId('69c37715b1c5d6989e3ab56e'), ObjectId('69c37715b1c5d6989e3ab56f'), ObjectId('69c37715b1c5d6989e3ab570'), ObjectId('69c37715b1c5d6989e3ab571'), ObjectId('69c37715b1c5d6989e3ab572'), ObjectId('69c37715b1c5d6989e3ab573'), ObjectId('69c37715b1c5d6989e3ab574'), ObjectId('69c37715b1c5d6989e3ab575'), ObjectId('69c37715b1c5d6989e3ab576'), ObjectId('69c37715b1c5d6989e3ab577'), ObjectId('69c37715b1c5d6989e3ab578'), ObjectId('69c37715b1c5d6989e3ab579'), ObjectId('69c37715b1c5d6989e3ab57a'), ObjectId('69c37715b1c5d6989e3ab57b'), ObjectId('69c37715b1c5d6989e3ab57c'), ObjectId('69c37715b1c5d6989e3ab57d'), ObjectId('69c37715b1c5d6989e3ab57e'), ObjectId('69c37715b1c5d6989e3ab57f'), ObjectId('69c37715b1c5d6989e3ab580'), ObjectId('69c37715b1c5d6989e3ab581'), ObjectId('69c37715b1c5d6989e3ab582'), ObjectId('69c37715b1c5d6989e3ab583'), ObjectId('69c37715b1c5d6989e3ab584'), ObjectId('69c37715b1c5d6989e3ab585'), ObjectId('69c37715b1c5d6989e3ab586'), ObjectId('69c37715b1c5d6989e3ab587'), ObjectId('69c37715b1c5d6989e3ab588'), ObjectId('69c37715b1c5d6989e3ab589'), ObjectId('69c37715b1c5d6989e3ab58a'), ObjectId('69c37715b1c5d6989e3ab58b'), ObjectId('69c37715b1c5d6989e3ab58c'), ObjectId('69c37715b1c5d6989e3ab58d'), ObjectId('69c37715b1c5d6989e3ab58e'), ObjectId('69c37715b1c5d6989e3ab58f'), ObjectId('69c37715b1c5d6989e3ab590'), ObjectId('69c37715b1c5d6989e3ab591'), ObjectId('69c37715b1c5d6989e3ab592'), ObjectId('69c37715b1c5d6989e3ab593'), ObjectId('69c37715b1c5d6989e3ab594'), ObjectId('69c37715b1c5d6989e3ab595'), ObjectId('69c37715b1c5d6989e3ab596'), ObjectId('69c37715b1c5d6989e3ab597'), ObjectId('69c37715b1c5d6989e3ab598'), ObjectId('69c37715b1c5d6989e3ab599'), ObjectId('69c37715b1c5d6989e3ab59a'), ObjectId('69c37715b1c5d6989e3ab59b'), ObjectId('69c37715b1c5d6989e3ab59c'), ObjectId('69c37715b1c5d6989e3ab59d'), ObjectId('69c37715b1c5d6989e3ab59e'), ObjectId('69c37715b1c5d6989e3ab59f'), ObjectId('69c37715b1c5d6989e3ab5a0'), ObjectId('69c37715b1c5d6989e3ab5a1'), ObjectId('69c37715b1c5d6989e3ab5a2'), ObjectId('69c37715b1c5d6989e3ab5a3'), ObjectId('69c37715b1c5d6989e3ab5a4'), ObjectId('69c37715b1c5d6989e3ab5a5'), ObjectId('69c37715b1c5d6989e3ab5a6'), ObjectId('69c37715b1c5d6989e3ab5a7'), ObjectId('69c37715b1c5d6989e3ab5a8'), ObjectId('69c37715b1c5d6989e3ab5a9'), ObjectId('69c37715b1c5d6989e3ab5aa'), ObjectId('69c37715b1c5d6989e3ab5ab'), ObjectId('69c37715b1c5d6989e3ab5ac'), ObjectId('69c37715b1c5d6989e3ab5ad'), ObjectId('69c37715b1c5d6989e3ab5ae'), ObjectId('69c37715b1c5d6989e3ab5af'), ObjectId('69c37715b1c5d6989e3ab5b0'), ObjectId('69c37715b1c5d6989e3ab5b1'), ObjectId('69c37715b1c5d6989e3ab5b2'), ObjectId('69c37715b1c5d6989e3ab5b3'), ObjectId('69c37715b1c5d6989e3ab5b4'), ObjectId('69c37715b1c5d6989e3ab5b5'), ObjectId('69c37715b1c5d6989e3ab5b6'), ObjectId('69c37715b1c5d6989e3ab5b7'), ObjectId('69c37715b1c5d6989e3ab5b8'), ObjectId('69c37715b1c5d6989e3ab5b9'), ObjectId('69c37715b1c5d6989e3ab5ba'), ObjectId('69c37715b1c5d6989e3ab5bb'), ObjectId('69c37715b1c5d6989e3ab5bc'), ObjectId('69c37715b1c5d6989e3ab5bd'), ObjectId('69c37715b1c5d6989e3ab5be'), ObjectId('69c37715b1c5d6989e3ab5bf'), ObjectId('69c37715b1c5d6989e3ab5c0'), ObjectId('69c37715b1c5d6989e3ab5c1'), ObjectId('69c37715b1c5d6989e3ab5c2'), ObjectId('69c37715b1c5d6989e3ab5c3'), ObjectId('69c37715b1c5d6989e3ab5c4'), ObjectId('69c37715b1c5d6989e3ab5c5'), ObjectId('69c37715b1c5d6989e3ab5c6'), ObjectId('69c37715b1c5d6989e3ab5c7'), ObjectId('69c37715b1c5d6989e3ab5c8'), ObjectId('69c37715b1c5d6989e3ab5c9'), ObjectId('69c37715b1c5d6989e3ab5ca'), ObjectId('69c37715b1c5d6989e3ab5cb'), ObjectId('69c37715b1c5d6989e3ab5cc'), ObjectId('69c37715b1c5d6989e3ab5cd'), ObjectId('69c37715b1c5d6989e3ab5ce'), ObjectId('69c37715b1c5d6989e3ab5cf'), ObjectId('69c37715b1c5d6989e3ab5d0'), ObjectId('69c37715b1c5d6989e3ab5d1'), ObjectId('69c37715b1c5d6989e3ab5d2'), ObjectId('69c37715b1c5d6989e3ab5d3'), ObjectId('69c37715b1c5d6989e3ab5d4'), ObjectId('69c37715b1c5d6989e3ab5d5'), ObjectId('69c37715b1c5d6989e3ab5d6'), ObjectId('69c37715b1c5d6989e3ab5d7'), ObjectId('69c37715b1c5d6989e3ab5d8'), ObjectId('69c37715b1c5d6989e3ab5d9'), ObjectId('69c37715b1c5d6989e3ab5da'), ObjectId('69c37715b1c5d6989e3ab5db'), ObjectId('69c37715b1c5d6989e3ab5dc'), ObjectId('69c37715b1c5d6989e3ab5dd'), ObjectId('69c37715b1c5d6989e3ab5de'), ObjectId('69c37715b1c5d6989e3ab5df'), ObjectId('69c37715b1c5d6989e3ab5e0'), ObjectId('69c37715b1c5d6989e3ab5e1'), ObjectId('69c37715b1c5d6989e3ab5e2'), ObjectId('69c37715b1c5d6989e3ab5e3'), ObjectId('69c37715b1c5d6989e3ab5e4'), ObjectId('69c37715b1c5d6989e3ab5e5'), ObjectId('69c37715b1c5d6989e3ab5e6'), ObjectId('69c37715b1c5d6989e3ab5e7'), ObjectId('69c37715b1c5d6989e3ab5e8'), ObjectId('69c37715b1c5d6989e3ab5e9'), ObjectId('69c37715b1c5d6989e3ab5ea'), ObjectId('69c37715b1c5d6989e3ab5eb'), ObjectId('69c37715b1c5d6989e3ab5ec'), ObjectId('69c37715b1c5d6989e3ab5ed'), ObjectId('69c37715b1c5d6989e3ab5ee'), ObjectId('69c37715b1c5d6989e3ab5ef'), ObjectId('69c37715b1c5d6989e3ab5f0'), ObjectId('69c37715b1c5d6989e3ab5f1'), ObjectId('69c37715b1c5d6989e3ab5f2'), ObjectId('69c37715b1c5d6989e3ab5f3'), ObjectId('69c37715b1c5d6989e3ab5f4'), ObjectId('69c37715b1c5d6989e3ab5f5'), ObjectId('69c37715b1c5d6989e3ab5f6'), ObjectId('69c37715b1c5d6989e3ab5f7'), ObjectId('69c37715b1c5d6989e3ab5f8'), ObjectId('69c37715b1c5d6989e3ab5f9'), ObjectId('69c37715b1c5d6989e3ab5fa'), ObjectId('69c37715b1c5d6989e3ab5fb'), ObjectId('69c37715b1c5d6989e3ab5fc'), ObjectId('69c37715b1c5d6989e3ab5fd'), ObjectId('69c37715b1c5d6989e3ab5fe'), ObjectId('69c37715b1c5d6989e3ab5ff'), ObjectId('69c37715b1c5d6989e3ab600'), ObjectId('69c37715b1c5d6989e3ab601'), ObjectId('69c37715b1c5d6989e3ab602'), ObjectId('69c37715b1c5d6989e3ab603'), ObjectId('69c37715b1c5d6989e3ab604'), ObjectId('69c37715b1c5d6989e3ab605'), ObjectId('69c37715b1c5d6989e3ab606'), ObjectId('69c37715b1c5d6989e3ab607'), ObjectId('69c37715b1c5d6989e3ab608'), ObjectId('69c37715b1c5d6989e3ab609'), ObjectId('69c37715b1c5d6989e3ab60a'), ObjectId('69c37715b1c5d6989e3ab60b'), ObjectId('69c37715b1c5d6989e3ab60c'), ObjectId('69c37715b1c5d6989e3ab60d'), ObjectId('69c37715b1c5d6989e3ab60e'), ObjectId('69c37715b1c5d6989e3ab60f'), ObjectId('69c37715b1c5d6989e3ab610'), ObjectId('69c37715b1c5d6989e3ab611'), ObjectId('69c37715b1c5d6989e3ab612'), ObjectId('69c37715b1c5d6989e3ab613'), ObjectId('69c37715b1c5d6989e3ab614'), ObjectId('69c37715b1c5d6989e3ab615'), ObjectId('69c37715b1c5d6989e3ab616'), ObjectId('69c37715b1c5d6989e3ab617'), ObjectId('69c37715b1c5d6989e3ab618'), ObjectId('69c37715b1c5d6989e3ab619'), ObjectId('69c37715b1c5d6989e3ab61a'), ObjectId('69c37715b1c5d6989e3ab61b'), ObjectId('69c37715b1c5d6989e3ab61c'), ObjectId('69c37715b1c5d6989e3ab61d'), ObjectId('69c37715b1c5d6989e3ab61e'), ObjectId('69c37715b1c5d6989e3ab61f'), ObjectId('69c37715b1c5d6989e3ab620'), ObjectId('69c37715b1c5d6989e3ab621'), ObjectId('69c37715b1c5d6989e3ab622'), ObjectId('69c37715b1c5d6989e3ab623'), ObjectId('69c37715b1c5d6989e3ab624'), ObjectId('69c37715b1c5d6989e3ab625'), ObjectId('69c37715b1c5d6989e3ab626'), ObjectId('69c37715b1c5d6989e3ab627'), ObjectId('69c37715b1c5d6989e3ab628'), ObjectId('69c37715b1c5d6989e3ab629'), ObjectId('69c37715b1c5d6989e3ab62a'), ObjectId('69c37715b1c5d6989e3ab62b'), ObjectId('69c37715b1c5d6989e3ab62c'), ObjectId('69c37715b1c5d6989e3ab62d'), ObjectId('69c37715b1c5d6989e3ab62e'), ObjectId('69c37715b1c5d6989e3ab62f'), ObjectId('69c37715b1c5d6989e3ab630'), ObjectId('69c37715b1c5d6989e3ab631'), ObjectId('69c37715b1c5d6989e3ab632'), ObjectId('69c37715b1c5d6989e3ab633'), ObjectId('69c37715b1c5d6989e3ab634'), ObjectId('69c37715b1c5d6989e3ab635'), ObjectId('69c37715b1c5d6989e3ab636'), ObjectId('69c37715b1c5d6989e3ab637'), ObjectId('69c37715b1c5d6989e3ab638'), ObjectId('69c37715b1c5d6989e3ab639'), ObjectId('69c37715b1c5d6989e3ab63a'), ObjectId('69c37715b1c5d6989e3ab63b'), ObjectId('69c37715b1c5d6989e3ab63c'), ObjectId('69c37715b1c5d6989e3ab63d'), ObjectId('69c37715b1c5d6989e3ab63e'), ObjectId('69c37715b1c5d6989e3ab63f'), ObjectId('69c37715b1c5d6989e3ab640'), ObjectId('69c37715b1c5d6989e3ab641'), ObjectId('69c37715b1c5d6989e3ab642'), ObjectId('69c37715b1c5d6989e3ab643'), ObjectId('69c37715b1c5d6989e3ab644'), ObjectId('69c37715b1c5d6989e3ab645'), ObjectId('69c37715b1c5d6989e3ab646'), ObjectId('69c37715b1c5d6989e3ab647'), ObjectId('69c37715b1c5d6989e3ab648'), ObjectId('69c37715b1c5d6989e3ab649'), ObjectId('69c37715b1c5d6989e3ab64a'), ObjectId('69c37715b1c5d6989e3ab64b'), ObjectId('69c37715b1c5d6989e3ab64c'), ObjectId('69c37715b1c5d6989e3ab64d'), ObjectId('69c37715b1c5d6989e3ab64e'), ObjectId('69c37715b1c5d6989e3ab64f'), ObjectId('69c37715b1c5d6989e3ab650'), ObjectId('69c37715b1c5d6989e3ab651'), ObjectId('69c37715b1c5d6989e3ab652'), ObjectId('69c37715b1c5d6989e3ab653'), ObjectId('69c37715b1c5d6989e3ab654'), ObjectId('69c37715b1c5d6989e3ab655'), ObjectId('69c37715b1c5d6989e3ab656'), ObjectId('69c37715b1c5d6989e3ab657'), ObjectId('69c37715b1c5d6989e3ab658'), ObjectId('69c37715b1c5d6989e3ab659'), ObjectId('69c37715b1c5d6989e3ab65a'), ObjectId('69c37715b1c5d6989e3ab65b'), ObjectId('69c37715b1c5d6989e3ab65c'), ObjectId('69c37715b1c5d6989e3ab65d'), ObjectId('69c37715b1c5d6989e3ab65e'), ObjectId('69c37715b1c5d6989e3ab65f'), ObjectId('69c37715b1c5d6989e3ab660'), ObjectId('69c37715b1c5d6989e3ab661'), ObjectId('69c37715b1c5d6989e3ab662'), ObjectId('69c37715b1c5d6989e3ab663'), ObjectId('69c37715b1c5d6989e3ab664'), ObjectId('69c37715b1c5d6989e3ab665'), ObjectId('69c37715b1c5d6989e3ab666'), ObjectId('69c37715b1c5d6989e3ab667'), ObjectId('69c37715b1c5d6989e3ab668'), ObjectId('69c37715b1c5d6989e3ab669'), ObjectId('69c37715b1c5d6989e3ab66a'), ObjectId('69c37715b1c5d6989e3ab66b'), ObjectId('69c37715b1c5d6989e3ab66c'), ObjectId('69c37715b1c5d6989e3ab66d'), ObjectId('69c37715b1c5d6989e3ab66e'), ObjectId('69c37715b1c5d6989e3ab66f'), ObjectId('69c37715b1c5d6989e3ab670'), ObjectId('69c37715b1c5d6989e3ab671'), ObjectId('69c37715b1c5d6989e3ab672'), ObjectId('69c37715b1c5d6989e3ab673'), ObjectId('69c37715b1c5d6989e3ab674'), ObjectId('69c37715b1c5d6989e3ab675'), ObjectId('69c37715b1c5d6989e3ab676'), ObjectId('69c37715b1c5d6989e3ab677'), ObjectId('69c37715b1c5d6989e3ab678'), ObjectId('69c37715b1c5d6989e3ab679'), ObjectId('69c37715b1c5d6989e3ab67a'), ObjectId('69c37715b1c5d6989e3ab67b'), ObjectId('69c37715b1c5d6989e3ab67c'), ObjectId('69c37715b1c5d6989e3ab67d'), ObjectId('69c37715b1c5d6989e3ab67e'), ObjectId('69c37715b1c5d6989e3ab67f'), ObjectId('69c37715b1c5d6989e3ab680'), ObjectId('69c37715b1c5d6989e3ab681'), ObjectId('69c37715b1c5d6989e3ab682'), ObjectId('69c37715b1c5d6989e3ab683'), ObjectId('69c37715b1c5d6989e3ab684'), ObjectId('69c37715b1c5d6989e3ab685'), ObjectId('69c37715b1c5d6989e3ab686'), ObjectId('69c37715b1c5d6989e3ab687'), ObjectId('69c37715b1c5d6989e3ab688'), ObjectId('69c37715b1c5d6989e3ab689'), ObjectId('69c37715b1c5d6989e3ab68a'), ObjectId('69c37715b1c5d6989e3ab68b'), ObjectId('69c37715b1c5d6989e3ab68c'), ObjectId('69c37715b1c5d6989e3ab68d'), ObjectId('69c37715b1c5d6989e3ab68e'), ObjectId('69c37715b1c5d6989e3ab68f'), ObjectId('69c37715b1c5d6989e3ab690'), ObjectId('69c37715b1c5d6989e3ab691'), ObjectId('69c37715b1c5d6989e3ab692'), ObjectId('69c37715b1c5d6989e3ab693'), ObjectId('69c37715b1c5d6989e3ab694'), ObjectId('69c37715b1c5d6989e3ab695'), ObjectId('69c37715b1c5d6989e3ab696'), ObjectId('69c37715b1c5d6989e3ab697'), ObjectId('69c37715b1c5d6989e3ab698'), ObjectId('69c37715b1c5d6989e3ab699'), ObjectId('69c37715b1c5d6989e3ab69a'), ObjectId('69c37715b1c5d6989e3ab69b'), ObjectId('69c37715b1c5d6989e3ab69c'), ObjectId('69c37715b1c5d6989e3ab69d'), ObjectId('69c37715b1c5d6989e3ab69e'), ObjectId('69c37715b1c5d6989e3ab69f'), ObjectId('69c37715b1c5d6989e3ab6a0'), ObjectId('69c37715b1c5d6989e3ab6a1'), ObjectId('69c37715b1c5d6989e3ab6a2'), ObjectId('69c37715b1c5d6989e3ab6a3'), ObjectId('69c37715b1c5d6989e3ab6a4'), ObjectId('69c37715b1c5d6989e3ab6a5'), ObjectId('69c37715b1c5d6989e3ab6a6'), ObjectId('69c37715b1c5d6989e3ab6a7'), ObjectId('69c37715b1c5d6989e3ab6a8'), ObjectId('69c37715b1c5d6989e3ab6a9'), ObjectId('69c37715b1c5d6989e3ab6aa'), ObjectId('69c37715b1c5d6989e3ab6ab'), ObjectId('69c37715b1c5d6989e3ab6ac'), ObjectId('69c37715b1c5d6989e3ab6ad'), ObjectId('69c37715b1c5d6989e3ab6ae'), ObjectId('69c37715b1c5d6989e3ab6af'), ObjectId('69c37715b1c5d6989e3ab6b0'), ObjectId('69c37715b1c5d6989e3ab6b1'), ObjectId('69c37715b1c5d6989e3ab6b2'), ObjectId('69c37715b1c5d6989e3ab6b3'), ObjectId('69c37715b1c5d6989e3ab6b4'), ObjectId('69c37715b1c5d6989e3ab6b5'), ObjectId('69c37715b1c5d6989e3ab6b6'), ObjectId('69c37715b1c5d6989e3ab6b7'), ObjectId('69c37715b1c5d6989e3ab6b8'), ObjectId('69c37715b1c5d6989e3ab6b9'), ObjectId('69c37715b1c5d6989e3ab6ba'), ObjectId('69c37715b1c5d6989e3ab6bb'), ObjectId('69c37715b1c5d6989e3ab6bc'), ObjectId('69c37715b1c5d6989e3ab6bd'), ObjectId('69c37715b1c5d6989e3ab6be'), ObjectId('69c37715b1c5d6989e3ab6bf'), ObjectId('69c37715b1c5d6989e3ab6c0'), ObjectId('69c37715b1c5d6989e3ab6c1'), ObjectId('69c37715b1c5d6989e3ab6c2'), ObjectId('69c37715b1c5d6989e3ab6c3'), ObjectId('69c37715b1c5d6989e3ab6c4'), ObjectId('69c37715b1c5d6989e3ab6c5'), ObjectId('69c37715b1c5d6989e3ab6c6'), ObjectId('69c37715b1c5d6989e3ab6c7'), ObjectId('69c37715b1c5d6989e3ab6c8'), ObjectId('69c37715b1c5d6989e3ab6c9'), ObjectId('69c37715b1c5d6989e3ab6ca'), ObjectId('69c37715b1c5d6989e3ab6cb'), ObjectId('69c37715b1c5d6989e3ab6cc'), ObjectId('69c37715b1c5d6989e3ab6cd'), ObjectId('69c37715b1c5d6989e3ab6ce'), ObjectId('69c37715b1c5d6989e3ab6cf'), ObjectId('69c37715b1c5d6989e3ab6d0'), ObjectId('69c37715b1c5d6989e3ab6d1'), ObjectId('69c37715b1c5d6989e3ab6d2'), ObjectId('69c37715b1c5d6989e3ab6d3'), ObjectId('69c37715b1c5d6989e3ab6d4'), ObjectId('69c37715b1c5d6989e3ab6d5'), ObjectId('69c37715b1c5d6989e3ab6d6'), ObjectId('69c37715b1c5d6989e3ab6d7'), ObjectId('69c37715b1c5d6989e3ab6d8'), ObjectId('69c37715b1c5d6989e3ab6d9'), ObjectId('69c37715b1c5d6989e3ab6da'), ObjectId('69c37715b1c5d6989e3ab6db'), ObjectId('69c37715b1c5d6989e3ab6dc'), ObjectId('69c37715b1c5d6989e3ab6dd'), ObjectId('69c37715b1c5d6989e3ab6de'), ObjectId('69c37715b1c5d6989e3ab6df'), ObjectId('69c37715b1c5d6989e3ab6e0'), ObjectId('69c37715b1c5d6989e3ab6e1'), ObjectId('69c37715b1c5d6989e3ab6e2'), ObjectId('69c37715b1c5d6989e3ab6e3'), ObjectId('69c37715b1c5d6989e3ab6e4'), ObjectId('69c37715b1c5d6989e3ab6e5'), ObjectId('69c37715b1c5d6989e3ab6e6'), ObjectId('69c37715b1c5d6989e3ab6e7'), ObjectId('69c37715b1c5d6989e3ab6e8'), ObjectId('69c37715b1c5d6989e3ab6e9'), ObjectId('69c37715b1c5d6989e3ab6ea'), ObjectId('69c37715b1c5d6989e3ab6eb'), ObjectId('69c37715b1c5d6989e3ab6ec'), ObjectId('69c37715b1c5d6989e3ab6ed'), ObjectId('69c37715b1c5d6989e3ab6ee'), ObjectId('69c37715b1c5d6989e3ab6ef'), ObjectId('69c37715b1c5d6989e3ab6f0'), ObjectId('69c37715b1c5d6989e3ab6f1'), ObjectId('69c37715b1c5d6989e3ab6f2'), ObjectId('69c37715b1c5d6989e3ab6f3'), ObjectId('69c37715b1c5d6989e3ab6f4'), ObjectId('69c37715b1c5d6989e3ab6f5'), ObjectId('69c37715b1c5d6989e3ab6f6'), ObjectId('69c37715b1c5d6989e3ab6f7'), ObjectId('69c37715b1c5d6989e3ab6f8'), ObjectId('69c37715b1c5d6989e3ab6f9'), ObjectId('69c37715b1c5d6989e3ab6fa'), ObjectId('69c37715b1c5d6989e3ab6fb'), ObjectId('69c37715b1c5d6989e3ab6fc'), ObjectId('69c37715b1c5d6989e3ab6fd'), ObjectId('69c37715b1c5d6989e3ab6fe'), ObjectId('69c37715b1c5d6989e3ab6ff'), ObjectId('69c37715b1c5d6989e3ab700'), ObjectId('69c37715b1c5d6989e3ab701'), ObjectId('69c37715b1c5d6989e3ab702'), ObjectId('69c37715b1c5d6989e3ab703'), ObjectId('69c37715b1c5d6989e3ab704'), ObjectId('69c37715b1c5d6989e3ab705'), ObjectId('69c37715b1c5d6989e3ab706'), ObjectId('69c37715b1c5d6989e3ab707'), ObjectId('69c37715b1c5d6989e3ab708'), ObjectId('69c37715b1c5d6989e3ab709'), ObjectId('69c37715b1c5d6989e3ab70a'), ObjectId('69c37715b1c5d6989e3ab70b'), ObjectId('69c37715b1c5d6989e3ab70c'), ObjectId('69c37715b1c5d6989e3ab70d'), ObjectId('69c37715b1c5d6989e3ab70e'), ObjectId('69c37715b1c5d6989e3ab70f'), ObjectId('69c37715b1c5d6989e3ab710'), ObjectId('69c37715b1c5d6989e3ab711'), ObjectId('69c37715b1c5d6989e3ab712'), ObjectId('69c37715b1c5d6989e3ab713'), ObjectId('69c37715b1c5d6989e3ab714'), ObjectId('69c37715b1c5d6989e3ab715'), ObjectId('69c37715b1c5d6989e3ab716'), ObjectId('69c37715b1c5d6989e3ab717'), ObjectId('69c37715b1c5d6989e3ab718'), ObjectId('69c37715b1c5d6989e3ab719'), ObjectId('69c37715b1c5d6989e3ab71a'), ObjectId('69c37715b1c5d6989e3ab71b'), ObjectId('69c37715b1c5d6989e3ab71c'), ObjectId('69c37715b1c5d6989e3ab71d'), ObjectId('69c37715b1c5d6989e3ab71e'), ObjectId('69c37715b1c5d6989e3ab71f'), ObjectId('69c37715b1c5d6989e3ab720'), ObjectId('69c37715b1c5d6989e3ab721'), ObjectId('69c37715b1c5d6989e3ab722'), ObjectId('69c37715b1c5d6989e3ab723'), ObjectId('69c37715b1c5d6989e3ab724'), ObjectId('69c37715b1c5d6989e3ab725'), ObjectId('69c37715b1c5d6989e3ab726'), ObjectId('69c37715b1c5d6989e3ab727'), ObjectId('69c37715b1c5d6989e3ab728'), ObjectId('69c37715b1c5d6989e3ab729'), ObjectId('69c37715b1c5d6989e3ab72a'), ObjectId('69c37715b1c5d6989e3ab72b'), ObjectId('69c37715b1c5d6989e3ab72c'), ObjectId('69c37715b1c5d6989e3ab72d'), ObjectId('69c37715b1c5d6989e3ab72e'), ObjectId('69c37715b1c5d6989e3ab72f'), ObjectId('69c37715b1c5d6989e3ab730'), ObjectId('69c37715b1c5d6989e3ab731'), ObjectId('69c37715b1c5d6989e3ab732'), ObjectId('69c37715b1c5d6989e3ab733'), ObjectId('69c37715b1c5d6989e3ab734'), ObjectId('69c37715b1c5d6989e3ab735'), ObjectId('69c37715b1c5d6989e3ab736'), ObjectId('69c37715b1c5d6989e3ab737'), ObjectId('69c37715b1c5d6989e3ab738'), ObjectId('69c37715b1c5d6989e3ab739'), ObjectId('69c37715b1c5d6989e3ab73a'), ObjectId('69c37715b1c5d6989e3ab73b'), ObjectId('69c37715b1c5d6989e3ab73c'), ObjectId('69c37715b1c5d6989e3ab73d'), ObjectId('69c37715b1c5d6989e3ab73e'), ObjectId('69c37715b1c5d6989e3ab73f'), ObjectId('69c37715b1c5d6989e3ab740'), ObjectId('69c37715b1c5d6989e3ab741'), ObjectId('69c37715b1c5d6989e3ab742'), ObjectId('69c37715b1c5d6989e3ab743'), ObjectId('69c37715b1c5d6989e3ab744'), ObjectId('69c37715b1c5d6989e3ab745'), ObjectId('69c37715b1c5d6989e3ab746'), ObjectId('69c37715b1c5d6989e3ab747'), ObjectId('69c37715b1c5d6989e3ab748'), ObjectId('69c37715b1c5d6989e3ab749'), ObjectId('69c37715b1c5d6989e3ab74a'), ObjectId('69c37715b1c5d6989e3ab74b'), ObjectId('69c37715b1c5d6989e3ab74c'), ObjectId('69c37715b1c5d6989e3ab74d'), ObjectId('69c37715b1c5d6989e3ab74e'), ObjectId('69c37715b1c5d6989e3ab74f'), ObjectId('69c37715b1c5d6989e3ab750'), ObjectId('69c37715b1c5d6989e3ab751'), ObjectId('69c37715b1c5d6989e3ab752'), ObjectId('69c37715b1c5d6989e3ab753'), ObjectId('69c37715b1c5d6989e3ab754'), ObjectId('69c37715b1c5d6989e3ab755'), ObjectId('69c37715b1c5d6989e3ab756'), ObjectId('69c37715b1c5d6989e3ab757'), ObjectId('69c37715b1c5d6989e3ab758'), ObjectId('69c37715b1c5d6989e3ab759'), ObjectId('69c37715b1c5d6989e3ab7